### ISSUE TITLE
how to create a new appId

### ISSUE THREAD

**Issue by deniapps** [algorand/smart-contracts#3]
Hello,
I see appId hardcoded in algosigner-react/src/App.js. I am wondering how to create a new one. I Googled it, but could not find the answer. Could you please tell me where I can apply for a new one?

Thanks!

**Comment by georgejr6** [comment]
what?

**Comment by algoanne** [comment]
@georgejr6 this repo (https://github.com/algorand/smart-contracts) is not being maintained and the content in it is out of date, we're going to archive it. If you are looking for smart contract examples, the developer relations github is the best place: https://github.com/orgs/algorand-devrel
